version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-SupportPortal
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - supportportal_data:/var/lib/mysql

volumes:
  supportportal_data: