server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal?createIfNotExist=true&
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
